In [139]:
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error as mse
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder as le, StandardScaler as ss

In [49]:
df = pd.read_csv('ds_salaries.csv')
df

Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT   
1             1       2020               SE              FT   
2             2       2020               SE              FT   
3             3       2020               MI              FT   
4             4       2020               SE              FT   
..          ...        ...              ...             ...   
602         602       2022               SE              FT   
603         603       2022               SE              FT   
604         604       2022               SE              FT   
605         605       2022               SE              FT   
606         606       2022               MI              FT   

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833   
1    Machine Learning Scientist  260000             USD         260000   
2             Big Data Engineer   85000             GBP         109024   
3          Product Data Analyst   20000             USD          20000   
4     Machine Learning Engineer  150000             USD         150000   
..                          ...     ...             ...            ...   
602               Data Engineer  154000             USD         154000   
603               Data Engineer  126000             USD         126000   
604                Data Analyst  129000             USD         129000   
605                Data Analyst  150000             USD         150000   
606                AI Scientist  200000             USD         200000   

    employee_residence  remote_ratio company_location company_size  
0                   DE             0               DE            L  
1                   JP             0               JP            S  
2                   GB            50               GB            M  
3                   HN             0               HN            S  
4                   US            50               US            L  
..                 ...           ...              ...          ...  
602                 US           100               US            M  
603                 US           100               US            M  
604                 US             0               US            M  
605                 US           100               US            M  
606                 IN           100               US            L  

[607 rows x 12 columns]

In [50]:
df.duplicated().sum()

0

In [51]:
df.isnull().sum()

Unnamed: 0            0
work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Unnamed: 0          607 non-null    int64 
 1   work_year           607 non-null    int64 
 2   experience_level    607 non-null    object
 3   employment_type     607 non-null    object
 4   job_title           607 non-null    object
 5   salary              607 non-null    int64 
 6   salary_currency     607 non-null    object
 7   salary_in_usd       607 non-null    int64 
 8   employee_residence  607 non-null    object
 9   remote_ratio        607 non-null    int64 
 10  company_location    607 non-null    object
 11  company_size        607 non-null    object
dtypes: int64(5), object(7)
memory usage: 57.0+ KB


In [53]:
df=df.drop(['Unnamed: 0','salary_currency','salary','company_location','remote_ratio'], axis=1)
df

work_year experience_level employment_type                   job_title  \
0         2020               MI              FT              Data Scientist   
1         2020               SE              FT  Machine Learning Scientist   
2         2020               SE              FT           Big Data Engineer   
3         2020               MI              FT        Product Data Analyst   
4         2020               SE              FT   Machine Learning Engineer   
..         ...              ...             ...                         ...   
602       2022               SE              FT               Data Engineer   
603       2022               SE              FT               Data Engineer   
604       2022               SE              FT                Data Analyst   
605       2022               SE              FT                Data Analyst   
606       2022               MI              FT                AI Scientist   

     salary_in_usd employee_residence company_size  
0            79833                 DE            L  
1           260000                 JP            S  
2           109024                 GB            M  
3            20000                 HN            S  
4           150000                 US            L  
..             ...                ...          ...  
602         154000                 US            M  
603         126000                 US            M  
604         129000                 US            M  
605         150000                 US            M  
606         200000                 IN            L  

[607 rows x 7 columns]

In [54]:
last_column = df.pop('salary_in_usd')
df.insert(6, 'salary_in_usd', last_column)
df

work_year experience_level employment_type                   job_title  \
0         2020               MI              FT              Data Scientist   
1         2020               SE              FT  Machine Learning Scientist   
2         2020               SE              FT           Big Data Engineer   
3         2020               MI              FT        Product Data Analyst   
4         2020               SE              FT   Machine Learning Engineer   
..         ...              ...             ...                         ...   
602       2022               SE              FT               Data Engineer   
603       2022               SE              FT               Data Engineer   
604       2022               SE              FT                Data Analyst   
605       2022               SE              FT                Data Analyst   
606       2022               MI              FT                AI Scientist   

    employee_residence company_size  salary_in_usd  
0                   DE            L          79833  
1                   JP            S         260000  
2                   GB            M         109024  
3                   HN            S          20000  
4                   US            L         150000  
..                 ...          ...            ...  
602                 US            M         154000  
603                 US            M         126000  
604                 US            M         129000  
605                 US            M         150000  
606                 IN            L         200000  

[607 rows x 7 columns]

In [99]:
x = df.iloc[:,:-1]
x

work_year experience_level employment_type                   job_title  \
0         2020               MI              FT              Data Scientist   
1         2020               SE              FT  Machine Learning Scientist   
2         2020               SE              FT           Big Data Engineer   
3         2020               MI              FT        Product Data Analyst   
4         2020               SE              FT   Machine Learning Engineer   
..         ...              ...             ...                         ...   
602       2022               SE              FT               Data Engineer   
603       2022               SE              FT               Data Engineer   
604       2022               SE              FT                Data Analyst   
605       2022               SE              FT                Data Analyst   
606       2022               MI              FT                AI Scientist   

    employee_residence company_size  
0                   DE            L  
1                   JP            S  
2                   GB            M  
3                   HN            S  
4                   US            L  
..                 ...          ...  
602                 US            M  
603                 US            M  
604                 US            M  
605                 US            M  
606                 IN            L  

[607 rows x 6 columns]

In [100]:
for z in list(x):
    x[z]=le().fit_transform(x[z])
x

work_year  experience_level  employment_type  job_title  \
0            0                 2                2         22   
1            0                 3                2         41   
2            0                 3                2          7   
3            0                 2                2         47   
4            0                 3                2         38   
..         ...               ...              ...        ...   
602          2                 3                2         17   
603          2                 3                2         17   
604          2                 3                2         12   
605          2                 3                2         12   
606          2                 2                2          1   

     employee_residence  company_size  
0                    14             0  
1                    32             2  
2                    20             1  
3                    23             2  
4                    55             0  
..                  ...           ...  
602                  55             1  
603                  55             1  
604                  55             1  
605                  55             1  
606                  27             0  

[607 rows x 6 columns]

In [101]:
y = df.iloc[:,-1:]
y

salary_in_usd
0            79833
1           260000
2           109024
3            20000
4           150000
..             ...
602         154000
603         126000
604         129000
605         150000
606         200000

[607 rows x 1 columns]

In [102]:
x=ss().fit_transform(x)
y=ss().fit_transform(y)

In [103]:
x

array([[-2.03202397, -0.12437139,  0.02785445,  0.09540616, -1.4463662 ,
        -1.24034577],
       [-2.03202397,  0.84349314,  0.02785445,  1.89920817, -0.46052733,
         1.82018221],
       [-2.03202397,  0.84349314,  0.02785445, -1.32864806, -1.11775324,
         0.28991822],
       ...,
       [ 0.85997732,  0.84349314,  0.02785445, -0.85396332,  0.79915567,
         0.28991822],
       [ 0.85997732,  0.84349314,  0.02785445, -0.85396332,  0.79915567,
         0.28991822],
       [ 0.85997732, -0.12437139,  0.02785445, -1.89826975, -0.73437146,
        -1.24034577]])

In [104]:
y

array([[-4.57904452e-01],
       [ 2.08328151e+00],
       [-4.61766700e-02],
       [-1.30182581e+00],
       [ 5.31773986e-01],
       [-5.68385892e-01],
       [ 1.09595854e+00],
       [-1.07988971e+00],
       [ 3.20204779e-01],
       [ 1.79158641e-01],
       [-8.60055202e-01],
       [-1.01294922e+00],
       [-1.02091832e+00],
       [-3.56816685e-01],
       [-3.85025913e-01],
       [-1.47108118e+00],
       [-9.95910842e-01],
       [ 2.46708053e-02],
       [-1.50342306e+00],
       [-7.94059714e-01],
       [-9.72751066e-01],
       [-1.49827487e+00],
       [-9.08321190e-01],
       [-2.01665933e-01],
       [ 3.81125023e-02],
       [ 3.00008141e+00],
       [-9.91524307e-01],
       [-1.11125837e+00],
       [-1.73456705e-01],
       [ 6.77886098e-02],
       [-7.47472174e-01],
       [-5.96595120e-01],
       [-6.18767573e-01],
       [ 4.76315814e+00],
       [-9.24400450e-01],
       [-5.38343065e-01],
       [-1.31142864e-01],
       [ 1.94223537e+00],
       [-1.4

In [105]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2,random_state=5)
print(f"Train set = {x_train.shape} and {y_train.shape}")
print(f"Test set = {x_test.shape} and {y_test.shape}")

Train set = (485, 6) and (485, 1)
Test set = (122, 6) and (122, 1)


In [106]:
from sklearn.svm import SVR
model = SVR(kernel = 'rbf').fit(x_train, y_train)

C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [108]:
y_pred = model.predict(x_test)
y_pred

array([-0.25874231, -0.68454978, -0.71898525, -0.02469606,  0.15145253,
       -0.89813868, -0.95834615,  0.31804216,  0.63162223, -1.12389693,
        0.15145253,  0.63162223, -0.06181327, -0.70899131, -0.61549216,
        0.15145253,  0.15145253,  0.63162223, -0.50634092,  0.64365424,
        0.36735169, -0.41954755, -0.96792345,  0.36735169, -0.32429853,
        0.71417049,  0.67074791, -0.33200861, -1.2049469 ,  0.09963419,
       -0.70797278, -0.461292  ,  0.63162223,  0.20320659, -0.92010634,
        0.8219753 ,  0.1004268 , -0.79110627,  0.67074791, -1.11902219,
        0.05410867, -0.44891231,  0.27130392,  0.0971198 ,  0.36735169,
        0.11969627,  0.15145253, -0.41580233, -0.85791922,  0.63162223,
       -0.84254157, -0.26584526, -0.32034497,  0.27130392,  0.15145253,
       -0.65690864, -0.16776409, -1.03937702, -0.69123703, -0.31223995,
        0.15145253,  0.67074791, -0.19373361, -1.02240504,  0.36735169,
        0.69241142,  0.32926904, -0.57609108, -0.14170451,  0.15

In [140]:
score = model.score(x_test, y_test)
print(f"Akurasi Model: {score * 100}%")
print(f"RMSE Model:", mse(y_test,y_pred,squared=False))

Akurasi Model: 40.05070598379222%
RMSE Model: 0.7371835177237838
